# Generated by Django 4.2 on 2024-10-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_answer_created_question_created_test_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='number_of_questions',
            field=models.IntegerField(default=5, verbose_name='number of questions'),
        ),
    ]
