# Generated by Django 4.2 on 2024-10-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_test_number_of_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='test',
            name='number_of_questions',
            field=models.IntegerField(default=1, verbose_name='number of questions'),
        ),
    ]
