# Generated by Django 4.2 on 2024-11-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_rename_text_answer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
