# Generated by Django 5.1.3 on 2024-11-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_question_is_available_test_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
