# Generated by Django 5.1.3 on 2024-12-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_science_test_sience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='sience',
            new_name='science',
        ),
    ]
