# Generated by Django 5.1.3 on 2024-12-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_rename_sience_test_science'),
    ]

    operations = [
        migrations.AddField(
            model_name='userattempt',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
